apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness2
spec:
  containers:
  - image: petrushevski/kubia-unhealthy
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 1
      periodSeconds: 10
      # exec:
      #   command:
      #   - ls -ltrh
      #   - /tmp
      # tcpSocket:
      #   port: 8080