apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia2
  template:
    metadata:
      labels:
        app: kubia2
    spec:
      containers:
      - name: nodejs
        # image: petrushevski/kubia:v1
        image: petrushevski/kubia:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubia2
spec:
  type: ClusterIP
  selector:
    app: kubia2
  ports:
  - port: 80
    targetPort: 8080


# kubectl get pod <pod_name> --output jsonpath={.spec.containers[0].image}
