apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 60
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
    # type: Recreate
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: petrushevski/kubia:v3
        name: nodejs
        readinessProbe:
          # initialDelaySeconds: 1
          failureThreshold: 3
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
          httpGet:
            path: /healthcheck
            port: 8080
  selector:
    matchLabels:
      app: kubia
