apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  namespace: default

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: curl-custom-sa
# spec:
#   serviceAccountName: foo
#   containers:
#   - name: main
#     image: curlimages/curl
#     command: ["sleep", "9999999"]
#   - name: ambassador
#     image: luksa/kubectl-proxy:1.6.2

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: curl-default-sa
# spec:
#   containers:
#   - name: main
#     image: curlimages/curl
#     command: ["sleep", "9999999"]
#   - name: ambassador
#     image: luksa/kubectl-proxy:1.6.2
---

apiVersion: v1
kind: Pod
metadata:
  name: kubectl-foo
  namespace: default
spec:
  serviceAccountName: foo
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]

---

apiVersion: v1
kind: Pod
metadata:
  name: kubectl-default
  namespace: default
spec:
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["sleep", "3600"]
