apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-default
  namespace: foo
subjects:
- kind: ServiceAccount
  name: default
  namespace: foo
roleRef:
  kind: ClusterRole 
  name: view
  apiGroup: rbac.authorization.k8s.io