apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: v1
kind: Namespace
metadata:
  name: bar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: foo
rules:
- apiGroups: [""]
  verbs: ["get", "list"]
  resources: ["services"]
---

apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: foo
spec:
  ports:
  - port: 8080
    targetPort: 80
  type: ClusterIP

