apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual1
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: petrushevski/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP

