apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-gpu
  labels:
    creation_method: manual
    env: prod
spec:
  nodeSelector:
    gpu: "false"
  containers:
  - image: petrushevski/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP