apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo2-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    # - ReadWriteMany
    # - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/mongodb
 
