apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo4-pvc 
spec:
  resources:
    requests:
      # storage: 1Gi
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
  # storageClassName: ""
  # storageClassName: managed-csi
  volumeName: mongo-pv
