apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    # - ReadWriteMany
    # - ReadWriteOncePod
  # persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/mongodb
