apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # name: slow
  name: slow-2
# provisioner: k8s.io/minikube-hostpath
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  # type: pd-ssd
  skuname: Standard_LRS
