apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # name: mongodb-pvc-new 
  name: mongodb-pvc-new-2
spec:
  # storageClassName: slow
  volumeName: pvc-5e0d5f4a-a653-47c6-ad76-92aa4ed18385
  storageClassName: slow-2
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
