apiVersion: v1
kind: Pod
metadata:
  # name: mongodb-new
  name: mongodb-new-2
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      # claimName: mongodb-pvc-new 
      claimName: mongodb-pvc-new-2

