apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: petrushevski/kubia
        # image: petrushevski/kubia2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080