apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kubia
  name: kubia-pod-3
spec:
  containers:
  - image: petrushevski/kubia
    imagePullPolicy: Always
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP