apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: petrushevski/kubia
        # image: petrushevski/kubia2
        ports:
        - containerPort: 8080