apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    # matchLabels:
    #   app: kubia
    #   app: kubia2
    matchExpressions:
    - key: app
      operator: In 
      values:
      - kubia
      - kubia2
  template:
    metadata:
      labels:
        app: kubia
        app: kubia2
    spec:
      containers:
      - name: kubia
        image: petrushevski/kubia
        # image: petrushevski/kubia2
        