apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-parallel-batch-job
spec:
  # backoffLimit: 5
  # activeDeadlineSeconds: 100
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: petrushevski/batch-job

        
        