apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage
spec:
  hard:
    requests.storage: 4Gi
    default.storageclass.storage.k8s.io/requests.storage: 2Gi
    managed-csi.storageclass.storage.k8s.io/requests.storage: 3Gi
