apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia2
spec:
  replicas: 2
  template:
    metadata:
      name: kubia2
      labels:
        app: kubia2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kubia2
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - nodepool1 
      containers:
      - image: petrushevski/kubia:v1
        name: nodejs
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
  selector:
    matchLabels:
      app: kubia2

