apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable
spec:
  containers:
  - image: busybox
    args: ["sleep", "9999999"]
    name: main
    resources:
      requests:
        cpu: 1.5
        memory: 2Gi
      limits: 
        cpu: 1.5
        memory: 2Gi      
  - image: busybox
    args: ["sleep", "9999999"]
    name: sidecar
  terminationGracePeriodSeconds: 0
